import { useCallback, useRef, useState } from "react";
import CarPreview from "./CarPreview.jsx";
import { WrapCanvas } from "./WrapCanvas.jsx";
import { containSize, fileStem } from "../core.js";

const MODELS=[{id:"model3",name:"Model 3",type:"Sedan"},{id:"modely",name:"Model Y",type:"Crossover"},{id:"models",name:"Model S",type:"Sedan"},{id:"modelx",name:"Model X",type:"SUV"},{id:"cybertruck",name:"Cybertruck",type:"Utility"}];
const Icon=({children})=><span className="grid size-7 place-items-center border border-black/15 font-mono text-sm">{children}</span>;

export default function App(){
  const [model,setModel]=useState("model3"),[layers,setLayers]=useState([]),[selectedId,setSelectedId]=useState(null),[tab,setTab]=useState("3d"),[autoRotate,setAutoRotate]=useState(true),[texture,setTexture]=useState(null),[revision,setRevision]=useState(0);
  const editor=useRef(null), selected=layers.find(l=>l.id===selectedId), modelData=MODELS.find(m=>m.id===model);
  const change=useCallback((id,patch)=>setLayers(v=>v.map(l=>l.id===id?{...l,...patch}:l)),[]);
  const files=e=>{[...(e.target.files||[])].filter(f=>f.type.startsWith("image/")).forEach((file,i)=>{const image=new Image(),url=URL.createObjectURL(file);image.onload=()=>{const size=containSize(image.width,image.height,600,310),layer={id:crypto.randomUUID(),name:file.name,url,image,x:1024+i*30,y:300+i*25,width:size.width,height:size.height,baseWidth:size.width,baseHeight:size.height,rotation:0,opacity:1,visible:true};setLayers(v=>[...v,layer]);setSelectedId(layer.id)};image.src=url});e.target.value=""};
  const remove=()=>{if(!selected)return;URL.revokeObjectURL(selected.url);setLayers(v=>v.filter(l=>l.id!==selected.id));setSelectedId(null)};
  const reorder=dir=>setLayers(v=>{const i=v.findIndex(l=>l.id===selectedId),n=Math.max(0,Math.min(v.length-1,i+dir));if(i<0||i===n)return v;const out=[...v],[item]=out.splice(i,1);out.splice(n,0,item);return out});
  const download=()=>{const a=document.createElement("a");a.href=editor.current.export();a.download=`${fileStem(modelData.name)}-wrap-template.png`;a.click()};
  const textureReady=useCallback(c=>{setTexture(c);setRevision(v=>v+1)},[]);
  return <div className="flex h-screen min-h-[680px] flex-col overflow-hidden bg-[#f6f6f2] text-ink">
    <header className="flex h-16 shrink-0 items-center justify-between border-b border-black/10 px-5 lg:px-7">
      <div className="flex items-center gap-3"><div className="grid size-8 grid-cols-2 gap-1 bg-ink p-2"><i className="-skew-x-12 bg-acid"/><i className="-skew-x-12 bg-acid"/></div><b className="font-mono text-xs tracking-[.16em]">WRAP / STUDIO <sup className="text-[7px] text-black/40">3D</sup></b></div>
      <div className="flex items-center gap-5"><span className="hidden text-[10px] text-black/45 sm:block"><i className="mr-2 inline-block size-1.5 rounded-full bg-green-600"/>Files stay on this device</span><button onClick={download} className="bg-ink px-5 py-2.5 text-xs font-bold text-white">Export wrap <b className="ml-5 text-acid">↓</b></button></div>
    </header>
    <main className="grid min-h-0 flex-1 grid-cols-1 lg:grid-cols-[260px_minmax(0,1fr)_270px]">
      <aside className="scroll-thin overflow-y-auto border-r border-black/10 bg-white/40 p-5">
        <p className="font-mono text-[9px] uppercase tracking-[.18em] text-black/45">01 / Vehicle</p><h1 className="mt-2 text-xl font-semibold">Choose your canvas.</h1>
        <label className="mt-6 block text-[9px] font-bold uppercase tracking-wider">Vehicle model</label><select value={model} onChange={e=>setModel(e.target.value)} className="mt-2 w-full border border-black/15 bg-white p-3 text-xs">{MODELS.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select>
        <div className="mt-3 border border-black/10 bg-[#ebebe6] p-4"><div className="relative h-20 overflow-hidden"><div className="absolute left-3 right-3 top-7 h-7 rounded-[60%_60%_25%_25%] bg-[#323630]"/><div className="absolute left-[24%] right-[24%] top-3 h-10 rounded-[60%_60%_10%_10%] bg-[#626760]"/><i className="absolute bottom-2 left-7 size-7 rounded-full border-[7px] border-ink bg-[#bbbdb7]"/><i className="absolute bottom-2 right-7 size-7 rounded-full border-[7px] border-ink bg-[#bbbdb7]"/></div><div className="flex justify-between font-mono text-[9px]"><b>{modelData.name.toUpperCase()}</b><span className="text-black/45">{modelData.type}</span></div></div>
        <div className="my-6 border-t border-black/10"/><div className="flex justify-between"><p className="font-mono text-[9px] uppercase tracking-[.18em] text-black/45">02 / Artwork</p><span className="text-[9px] text-black/45">{layers.length} layers</span></div>
        <label className="mt-3 flex h-24 cursor-pointer flex-col items-center justify-center border border-dashed border-black/30 bg-white/30 hover:bg-acid/15"><input type="file" multiple accept="image/*" onChange={files} className="hidden"/><b className="text-xl font-light">＋</b><strong className="text-[10px]">Add artwork</strong><span className="mt-1 text-[8px] text-black/40">PNG, JPG, WEBP or SVG</span></label>
        <div className="mt-3 space-y-1.5">{[...layers].reverse().map(l=><button key={l.id} onClick={()=>setSelectedId(l.id)} className={`flex w-full items-center gap-2 border p-1.5 text-left ${l.id===selectedId?"border-ink bg-white shadow-[inset_3px_0_#dfff36]":"border-black/10 bg-white/60"}`}><img src={l.url} className="size-8 object-cover"/><span className="min-w-0 flex-1 truncate text-[9px] font-semibold">{l.name}</span><span onClick={e=>{e.stopPropagation();change(l.id,{visible:!l.visible})}} className="px-1 text-xs">{l.visible?"◉":"○"}</span></button>)}</div>
      </aside>
      <section className="flex min-h-0 flex-col bg-canvas p-4 lg:p-5">
        <div className="mb-3 flex items-end justify-between"><div><p className="font-mono text-[9px] uppercase tracking-[.18em] text-black/45">Live preview</p><h2 className="mt-1 text-base font-semibold">{modelData.name} / custom wrap</h2></div><div className="flex border border-black/15 bg-[#f5f5f0] p-1"><button onClick={()=>setTab("3d")} className={`px-4 py-1.5 text-[9px] font-bold ${tab==="3d"?"bg-ink text-white":""}`}>3D CAR</button><button onClick={()=>setTab("2d")} className={`px-4 py-1.5 text-[9px] font-bold ${tab==="2d"?"bg-ink text-white":""}`}>2D TEMPLATE</button></div></div>
        <div className="checkerboard relative min-h-0 flex-1 overflow-hidden border border-black/10">{tab==="3d"?<><CarPreview textureCanvas={texture} textureRevision={revision} model={model} autoRotate={autoRotate}/><div className="pointer-events-none absolute inset-x-0 bottom-4 text-center font-mono text-[8px] text-black/50">DRAG TO ORBIT · LIVE WRAP TEXTURE</div></>:<div className="flex h-full items-center p-3"><WrapCanvas ref={editor} layers={layers} selectedId={selectedId} onSelect={setSelectedId} onChange={change} model={modelData.name} onTexture={textureReady}/></div>}</div>
        <div className="mt-2 flex items-center justify-between text-[8px] text-black/45"><span>{tab==="3d"?"Drag the vehicle to inspect every angle":"Drag artwork directly on the print template"}</span><label className="flex items-center gap-2"><input type="checkbox" checked={autoRotate} onChange={e=>setAutoRotate(e.target.checked)}/> AUTO ROTATE</label></div>
        <div className="fixed -left-[9999px] top-0"><WrapCanvas ref={tab==="2d"?undefined:editor} layers={layers} selectedId={selectedId} onSelect={setSelectedId} onChange={change} model={modelData.name} onTexture={textureReady}/></div>
      </section>
      <aside className="scroll-thin flex overflow-y-auto border-l border-black/10 bg-white/40 p-5"><div className="flex w-full flex-col"><p className="font-mono text-[9px] uppercase tracking-[.18em] text-black/45">03 / Fine tune</p><h2 className="mt-2 text-xl font-semibold">Layer controls.</h2>
        {!selected?<p className="mt-6 border border-dashed border-black/15 p-4 text-[10px] leading-relaxed text-black/45">Select artwork on the canvas or in the layer list to edit it.</p>:<div className="mt-6"><div className="truncate bg-black/5 p-3 text-[10px] font-bold">{selected.name}</div>
          {[{label:"Scale",value:Math.round(selected.width/selected.baseWidth*100),min:10,max:300,suffix:"%",set:v=>change(selected.id,{width:selected.baseWidth*v/100,height:selected.baseHeight*v/100})},{label:"Rotation",value:Math.round(selected.rotation*180/Math.PI),min:-180,max:180,suffix:"°",set:v=>change(selected.id,{rotation:v*Math.PI/180})},{label:"Opacity",value:Math.round(selected.opacity*100),min:10,max:100,suffix:"%",set:v=>change(selected.id,{opacity:v/100})}].map(c=><label key={c.label} className="mt-5 block"><span className="flex justify-between text-[9px]"><b>{c.label}</b><em className="font-mono not-italic text-black/45">{c.value}{c.suffix}</em></span><input className="range mt-2" type="range" min={c.min} max={c.max} value={c.value} onChange={e=>c.set(+e.target.value)}/></label>)}
          <div className="mt-6 grid grid-cols-2 gap-1.5"><button onClick={()=>reorder(1)} className="border border-black/15 p-2 text-[9px]">Move forward</button><button onClick={()=>reorder(-1)} className="border border-black/15 p-2 text-[9px]">Move back</button><button onClick={()=>{const copy={...selected,id:crypto.randomUUID(),name:`${selected.name} copy`,x:selected.x+30,y:selected.y+30};setLayers(v=>[...v,copy]);setSelectedId(copy.id)}} className="border border-black/15 p-2 text-[9px]">Duplicate</button><button onClick={remove} className="border border-red-300 p-2 text-[9px] text-red-700">Delete</button></div>
        </div>}
        <div className="mt-auto bg-acid p-4"><p className="font-mono text-[9px] uppercase tracking-[.18em] text-black/50">04 / Export</p><h3 className="mt-2 text-lg font-semibold">Ready for the road?</h3><p className="mt-2 text-[9px] leading-relaxed">Download your artwork and vehicle guides in one high-resolution PNG.</p><button onClick={download} className="mt-4 flex w-full justify-between bg-ink p-3 text-[10px] font-bold text-white">Download template <b className="text-acid">↓</b></button><p className="mt-2 text-center font-mono text-[8px]">PNG · 2048 × 1024 PX</p></div>
      </div></aside>
    </main>
  </div>
}
